### ISSUE TITLE
Active Input Einheit hat für zwei Werte "AC Input"

### ISSUE THREAD

**Issue by MatthiasOs** [CommentSectionScientist/ModbusTCP#23]
Active Input Einheit bei Register 29 "Active Input" hat für 0 und 1 jeweils "AC Input" als Wert.
Soll eines davon vllt eher DC oder so sein? Oder Output?

**Comment by OliOssi** [comment]
Ac input 0- Netz
Ac input 1- Generator (findet keine Anwendung derzeit)
Ac input 240- Netz Ausfall (wichtig!!!)
